### PR TITLE
initial ONB implementation

### PR DESCRIPTION
**Pull request by mateuszbaran**
I've implemented the key parts of ONBs discussed in https://github.com/JuliaNLSolvers/Manifolds.jl/issues/66 . I'll probably add `ProjectedONB` here as well, and then make a PR to `Manifolds.jl` to add the ONB functionality.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I could change the default implementations of `represent_in_basis` and `inverse_represent_in_basis` so that they try to use `basis`. What do you think? Or maybe have a `PrecalculatedBasis` struct that inherits from `AbstractBasis` that holds basis vectors and then implement `represent_in_basis` and `inverse_represent_in_basis` for this type?

**Comment by mateuszbaran** [comment]
I've added `ProjectedONB`.

**Comment by kellertuer** [comment]
Thanks for starting this. While I did not have time to check your interface idea, could you also include the diagonalizing one that includes the eigenvalues? And – should we write out `ONB`? Or is `ProjectedOrthoNormalBasis` too long?

I have to check in what sence the projected one is orthonormal (in the embedding before projecting? We could do Gram Schmidt in a tangent space?).

**Comment by mateuszbaran** [comment]
> could you also include the diagonalizing one that includes the eigenvalues?

Sure, I can add a struct for that basis here. How would you call that struct? I think I need to tweak the return type of `basis` to let this function return kappas in a reasonable way.

> And – should we write out `ONB`? Or is `ProjectedOrthoNormalBasis` too long?

I don't have a preference here, I can expand all `ONB`s to `OrthonormalBasis` if you prefer it.

> I have to check in what sence the projected one is orthonormal (in the embedding before projecting? We could do Gram Schmidt in a tangent space?).

It assumes that the tangent space is a linear subspace of the ambient space of size specified by `representation_size`. It returns an ONB of the tangent space at a given point. We could use Gram-Schmidt instead of SVD but as far as I know SVD is more numerically stable.

**Comment by kellertuer** [comment]
> > could you also include the diagonalizing one that includes the eigenvalues?
> 
> Sure, I can add a struct for that basis here. How would you call that struct? I think I need to tweak the return type of `basis` to let this function return kappas in a reasonable way.

Yes, that would be nice. Maybe since we return a `Basis` anyways, the one with the kappas might just have fields for that?


> I don't have a preference here, I can expand all `ONB`s to `OrthonormalBasis` if you prefer it.
I would prefer that for readability, yes.

> 
> > I have to check in what sence the projected one is orthonormal (in the embedding before projecting? We could do Gram Schmidt in a tangent space?).
> 
> It assumes that the tangent space is a linear subspace of the ambient space of size specified by `representation_size`. It returns an ONB of the tangent space at a given point. We could use Gram-Schmidt instead of SVD but as far as I know SVD is more numerically stable.

That would also imply that all tangent spaces get their metric by restricting the inner from the ambient space to the tangent? Otherwise you loose normality. By projection you will loose orthogonality anyways (in general) I think.

**Comment by mateuszbaran** [comment]
> Yes, that would be nice. Maybe since we return a `Basis` anyways, the one with the kappas might just have fields for that?

Yes, I'll do something like that.

**Comment by mateuszbaran** [comment]
> I would prefer that for readability, yes.

OK, I'll change it then.

> That would also imply that all tangent spaces get their metric by restricting the inner from the ambient space to the tangent? Otherwise you loose normality. By projection you will loose orthogonality anyways (in general) I think.

Projection both destroys orthogonality and changes the norm. I restore orthogonality using SVD. This assumes that orthogonalization in ambient space coincides with orthogonalization in the tangent space, which doesn't have to be true for all embedded manifolds but for many it is. Probably a `MetricManifold` with a non-diagonal metric wouldn't work here. I could add Gram-Schmidt for that case. Finally I normalize all vectors by dividing by their norm.

The SVD-based approach won't work for all manifolds but I still think it works for sufficiently many to put this method here.

**Comment by kellertuer** [comment]
Great and thanks for the clarification. It sounds reasonable using SVD, the advantage of Gram schmidt (using the inner product on the tangent) would be, that it always returns orthonormals.

**Comment by mateuszbaran** [comment]
BTW, could you write a docstring for that diagonalizing basis with kappas? I've read the one you have in Manopt.jl and the symbols aren't properly explained. What's the first vector that's mentioned there? What's `\Xi`? Why does it say that `\kappa_1` is zero but for sphere all kappas are equal to 1?

**Comment by kellertuer** [comment]
Can you link that? The first one should be zero. As I linked the paper a few times, it's the curvature tensors diagonalization along the geodesic pointing towards the first tangent vectors direction. Since that's along a geodesic, that direction is not getting any (additional) curvature and is hence zero. I can't find the one you referring to, but Manopt.jl also does not have it that often, the matlab code does, see [here](https://github.com/kellertuer/MVIRT/blob/master/manifolds/Sn.m#L227).

\Xi is  the set of vectors (\xi_1,...\xi_n), i.e. the whole ONB, \kappa_1, ..., \kappa_n are above eigen values of the diagonalized curvature tensor along the geodesic indicated by the first, so \xi_1.

**Comment by sethaxen** [comment]
Thanks for getting started on this. I haven't had a chance to look at the code yet, but I wonder why this PR is in our base package and not in Manifolds.jl. In our past discussions, we agreed new features would appear in Manifolds first and only after the interfaces settle would the interface perhaps end up in Manifolds.jl.

**Comment by mateuszbaran** [comment]
Right, I forgot. I'll move it to `Manifolds.jl`.

**Comment by kellertuer** [comment]
I just noticed, that if you provide a direction (x not y) then the function is actually correct, see a few lines after where the first component is set to zero (sadly, kind of, since I hoped I had found a bug why my bezier curves to not yet work).

**Comment by mateuszbaran** [comment]
Right, I see, when the tangent vector is non-zero then it works.

**Comment by kellertuer** [comment]
I would phrase that differently: if you have the zero vector, you do not get a direction for the geodesic and the resulting ONB is a classical one (hence all curvature Eigenvalues stay one). So then also it works :)

**Pull request closed without merging**
